# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize
from PyQt5.QtWidgets import QMainWindow


class Ui_MainWindow(QMainWindow):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(490, 315)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
		MainWindow.setSizePolicy(sizePolicy)
		MainWindow.setMinimumSize(QSize(490, 315))
		MainWindow.setMaximumSize(QSize(490, 315))
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.download_btn = QtWidgets.QPushButton(self.centralwidget)
		self.download_btn.setEnabled(True)
		self.download_btn.setGeometry(QtCore.QRect(280, 30, 201, 71))
		font = QtGui.QFont()
		font.setFamily("OCR A Extended")
		font.setPointSize(12)
		self.download_btn.setFont(font)
		self.download_btn.setObjectName("download_btn")
		self.edit_btn = QtWidgets.QPushButton(self.centralwidget)
		self.edit_btn.setGeometry(QtCore.QRect(280, 120, 201, 71))
		font = QtGui.QFont()
		font.setFamily("OCR A Extended")
		font.setPointSize(12)
		self.edit_btn.setFont(font)
		self.edit_btn.setObjectName("edit_btn")
		self.exit_btn = QtWidgets.QPushButton(self.centralwidget)
		self.exit_btn.setGeometry(QtCore.QRect(370, 230, 111, 41))
		font = QtGui.QFont()
		font.setFamily("OCR A Extended")
		font.setPointSize(11)
		self.exit_btn.setFont(font)
		self.exit_btn.setObjectName("exit_btn")
		self.label = QtWidgets.QLabel(self.centralwidget)
		self.label.setGeometry(QtCore.QRect(0, 0, 261, 231))
		font = QtGui.QFont()
		font.setFamily("Papyrus")
		font.setPointSize(27)
		self.label.setFont(font)
		self.label.setObjectName("label")
		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 491, 21))
		self.menubar.setObjectName("menubar")
		self.menuAbout = QtWidgets.QMenu(self.menubar)
		self.menuAbout.setObjectName("menuAbout")
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)
		self.actionAbout = QtWidgets.QAction(MainWindow)
		self.actionAbout.setObjectName("actionAbout")
		self.actionInfo = QtWidgets.QAction(MainWindow)
		self.actionInfo.setObjectName("actionInfo")
		self.menuAbout.addAction(self.actionAbout)
		self.menubar.addAction(self.menuAbout.menuAction())

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
		self.download_btn.setText(_translate("MainWindow", "Download Subtitles"))
		self.edit_btn.setText(_translate("MainWindow", "Convert to .srt"))
		self.exit_btn.setText(_translate("MainWindow", "EXIT"))
		self.label.setText(_translate("MainWindow", "Anime Subtitle \n Downloader"))
		self.menuAbout.setTitle(_translate("MainWindow", "Details"))
		self.actionAbout.setText(_translate("MainWindow", "About"))
		self.actionInfo.setText(_translate("MainWindow", "Info"))

	def downloadCallActions(self):
		pass

# import rsrc_rc
